### ISSUE TITLE
Package installation error: javabridge

### ISSUE THREAD

**Issue by shenxiangzhuang** [salesforce/PyRCA#25]
There is an error in the installation of `javabridge` package and the issue is similar to LeeKamentsky/python-javabridge#192. 

Fortunately I solved the problem by the solution provided in the issue: `pip install git+https://github.com/LeeKamentsky/python-javabridge`.

I think it will be better to solve the installation error within this repo. Maybe we can try to use some building tools like [poetry](https://github.com/python-poetry/poetry) or [rye](https://github.com/mitsuhiko/rye) to manage these dependencies which are more flexible and convenient.

**Comment by yangwenz** [comment]
Hi, thanks for raising this issue. We will do this after revising the docs and technical report.

**Comment by keonho-kim** [comment]
@yangwenz 
> Hi, thanks for raising this issue. We will do this after revising the docs and technical report.

Hello, I encounter similar issue on Macbook Pro with M1 MAX. 
Following the maintainer (Check this [link](https://github.com/LeeKamentsky/python-javabridge/issues/201), the issue would not be solved easily. (Yeah.. the thread had been made on March, but it still...)

Can you give any idea to install PyRCA without installing UI/UX, to use it on the Jupyter Notebook or Python Script? 

Thanks you for your Work :)

**Comment by yangwenz** [comment]
Hi, a quick solution is that you can download the repo and remove the javabridge dependency in the setup.py, and then install the lib. If javabridge is not installed, you cannot use FGES for causal discovery and can use other methods such as PC.

**Comment by algolabs-kh** [comment]
@yangwenz 

Thanks :) 
Is there any update plan for javabridge dependency? 
This library is somewhat subtle IMO ..

**Comment by keonho-kim** [comment]
@yangwenz 

Thanks :)
Is there any update plan for javabridge dependency?
This library is somewhat subtle IMO ..

**Comment by yangwenz** [comment]
It is quite tricky to update javabridge. We will replace the java implementation of FGES with a python implementation, then the javabridge dependency will be removed.

**Comment by chenghaoliu89** [comment]
Hi @shenxiangzhuang we have replaced javabridge with jpype, and merged it into main branch. I will close this issue
