### ISSUE TITLE
Causal Graph Generation using Dashboard : 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by widyaputeriaulia10** [salesforce/PyRCA#30]
Dear Authors @

I would lite to re-impplement the example that you publish on the paper. I have convert data_linear.txt to csv (similar to the data on the paper) i able to load data on "Data Analysis" Tab, but when move to "Causal Discovery" tab and choose "Causal Discovery Algorithm" I encountered an error with the following message: 'NoneType' object is not subscriptable

Do you have any Suggestion ?

Here i Attached URL to data

https://drive.google.com/file/d/1aBpvY4RN_xzOnp7hH3cwn1XJNQAYdTOg/view?usp=sharing

**Comment by yangwenz** [comment]
The tool doesn't include preprocessing functions. The data needs to be preprocessed before using it to generate causal graphs. The input data cannot include missing values or NaNs.

**Comment by widyaputeriaulia10** [comment]
Thank You for the respond.

I have check to the dataset and i found no Missing Value.

Pada tanggal Sen, 26 Jun 2023 pukul 11.41 Yang Wenzhuo <
***@***.***> menulis:

**Comment by yangwenz** [comment]
If the data has no missing values or NaNs, please try to use the PC algorithm first to see if there are any issues. FGES needs to install py-causal which may have dependency issues on some platforms (e.g., javabridge).

**Comment by widyaputeriaulia10** [comment]
Thank you for the suggestion, but the problem is still the same.

if possible, may i request .csv data that you are using?

Thank You in Advance 🙏

Pada tanggal Sen, 26 Jun 2023 13.02, Yang Wenzhuo ***@***.***>
menulis:

**Comment by yangwenz** [comment]
[df.csv](https://github.com/salesforce/PyRCA/files/11864365/df.csv)
You can try this toy dataset

**Comment by widyaputeriaulia10** [comment]
Unfortunately, There is same problem occurred.

Pada tanggal Sen, 26 Jun 2023 pukul 13.21 Yang Wenzhuo <
***@***.***> menulis:

**Comment by yangwenz** [comment]
Could you please list the versions of the installed PyRCA dependencies? Especially those related to Plotly and Dash.

**Comment by yangwenz** [comment]
Or you can try to reinstall the latest version of all these dependencies.

**Comment by widyaputeriaulia10** [comment]
Plotly = 5.9.0
dash = 2.10.2
dash-boostrap-components = 1.4.1
jupyter-dash = 0.4.2


Pada tanggal Sen, 26 Jun 2023 pukul 13.56 Yang Wenzhuo <
***@***.***> menulis:

**Comment by yangwenz** [comment]
Could you first try the code for building causal graphs instead of using the dashboard to check if the libs for causal discovery work OK?

**Comment by yangwenz** [comment]
> 

I tested these versions. The dashboard works fine. Probably there are some issues with the causal discovery libs. You can clone this repo and run the tests to see if there are any issues, e.g., in the root folder, PYTHONPATH=. pytest tests/

**Comment by widyaputeriaulia10** [comment]
Thank You for the response.

Actually I successfully generated the network graph with the data you
provided (synthetic0.pkl), I found that the root causes are nodes x18 and
x2. I'm a bit confused about how to interpret the graph. I thought that the
nodes at the arrowhead were the causes, and the nodes at the arrow tail
were the effects. However, I found that node x18 is at the arrow tail,
which I thought would be an effect. Am I misunderstanding how to read the
root causes generated by PyRCA?

Pada tanggal Sen, 26 Jun 2023 pukul 15.14 Yang Wenzhuo <
***@***.***> menulis:

**Comment by widyaputeriaulia10** [comment]
here, I attach the root cause graph that i generated

[image: image.png]

Pada tanggal Rab, 5 Jul 2023 pukul 16.06 widya puteri aulia <
***@***.***> menulis:

**Comment by yangwenz** [comment]
Hi, the dashboard can only run causal discovery given the data. But because of noise or other data issues, the results usually are not accurate. That's why it requires the domain knowledge to refine the results. If you find some errors, you can iteratively revise the graph by adding constraints.

**Comment by widyaputeriaulia10** [comment]
Thank you for the clarification.

Pada tanggal Rab, 5 Jul 2023 18.46, Yang Wenzhuo ***@***.***>
menulis:

**Comment by widyaputeriaulia10** [comment]
I want to confirm if it is true that the RCA graph which generated by PyRCA
located at the arrowhead as shown on the #28
<https://github.com/salesforce/PyRCA/issues/28>

Pada tanggal Rab, 5 Jul 2023 pukul 18.56 widya puteri aulia <
***@***.***> menulis:

**Comment by yangwenz** [comment]
The parent nodes are the causes and the children are effects. So the arrow directions are different from the ones in the service graph.

**Comment by widyaputeriaulia10** [comment]
Ok, thanks for the clarification.

Pada tanggal Kam, 6 Jul 2023 pukul 09.39 Yang Wenzhuo <
***@***.***> menulis:
