### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by kingshukb** [salesforce/PyRCA#34]
While trying to run a simulation, i am getting the following import error:
`▶ python3.7 test.py             
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from pyrca.graphs.causal.pc import PC
ModuleNotFoundError: No module named 'pyrca.graphs'`

i have created a `test.py` file inside example folder with the following code:

```import networkx as nx
import numpy as np
import pandas as pd

from pyrca.graphs.causal.pc import PC
from rca import RCAEngine


df = pd.read_csv("XXXX.csv")


engine = RCAEngine()
engine.build_causal_graph(
    df=df,
    run_pdag2dag=True,
    max_num_points=5000000,
    verbose=True,
    method_class=PC
)```

i am using conda env. Please help

**Comment by yangwenz** [comment]
If the wrong lib was install, please run "pip uninstall pyrca, pip install sfr-pyrca[all]".

**Comment by kingshukb** [comment]
Hi, I had cloned the repo and installed the project. the code editor is able to link the import but while running the code i am facing this error.

**Comment by yangwenz** [comment]
Please check your python environment, especially the one used to run the code. Probably there are some installation issues.
