### ISSUE TITLE
Unable to Run DataGeneration.ipynb

### ISSUE THREAD

**Issue by suciokhan** [salesforce/PyRCA#37]
Hello, I'm attempting to run your example `DataGeneration.ipynb` script here: https://github.com/salesforce/PyRCA/blob/main/examples/DataGeneration.ipynb

Unfortunately, it throws an error on this line: 

`graph_matrix = DAGGen(DAGGenConfig).gen()`

Error as follows:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 graph_matrix = DAGGen(DAGGenConfig).gen() # create a DAG
      2 G = nx.DiGraph(graph_matrix)
      4 # transform node names from 0 to N-1 to X1 to XN

File [~/anaconda3/envs/pyrca/lib/python3.9/site-packages/pyrca/simulation/data_gen.py:70](https://file+.vscode-resource.vscode-cdn.net/home/suciokhan/rca/~/anaconda3/envs/pyrca/lib/python3.9/site-packages/pyrca/simulation/data_gen.py:70), in DAGGen.gen(self)
     68 # Make the graphs connected
     69 for cause in range(1, self.config.num_node):
---> 70     result = self.config.rng.integers(low=0, high=cause)
     71     matrix[cause, result] = 1
     72 num_edge -= self.config.num_node - 1

AttributeError: 'NoneType' object has no attribute 'integers'
```

I'm running this in an Anaconda environment with Python 3.9, and using version '1.0.1' for PyRCA.

**Comment by yangwenz** [comment]
Hi, there is an error in this notebook. You can try "graph_matrix = DAGGen(DAGGenConfig()).gen()". Thanks for raising this issue, and the problem has been fixed in the main branch.

**Comment by suciokhan** [comment]
Thanks for the help- confirming that fixed the problem.
